# Generated by Django 5.2.5 on 2025-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="blog_images/")),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="candidate_images/")),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="employer_images/")),
                ("title", models.CharField(max_length=255)),
                ("open", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
