# Generated by Django 5.2.5 on 2025-12-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_profile_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dropdown Group',
                'verbose_name_plural': 'Dropdown Groups',
                'db_table': 'dropdown_group',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('assign_roles', 'Can assign roles and manage user roles'), ('manage_platform', 'Can manage platform settings and content'), ('review_candidates', 'Can review and shortlist candidates'), ('apply_jobs', 'Can apply to jobs'))},
        ),
        migrations.CreateModel(
            name='DropdownMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.dropdowngroup')),
            ],
            options={
                'verbose_name': 'Dropdown Master',
                'verbose_name_plural': 'Dropdown Masters',
                'db_table': 'dropdown_master',
                'ordering': ['group', 'sort_order', 'text'],
            },
        ),
    ]
