# Generated by Django 5.2.5 on 2025-12-15 01:29

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_profile_options_profile_about_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX, or TXT - Max 5MB)', null=True, upload_to='candidate-resume/', validators=[App.models.validate_resume_file]),
        ),
    ]
