# Generated by Django 5.1.15 on 2025-12-15 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_profile_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_path', models.CharField(help_text='Path to the uploaded resume file', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, help_text='Full extracted text from resume', null=True)),
                ('resume_json', models.JSONField(blank=True, help_text='Structured JSON data extracted from resume', null=True)),
                ('extracted_skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('extracted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extracted_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Resume sentiment polarity score', null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_processing', to='App.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_processing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Processing',
                'verbose_name_plural': 'Resume Processings',
                'db_table': 'resume_processing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='resume_proc_user_id_40588e_idx'), models.Index(fields=['status', 'created_at'], name='resume_proc_status_e34451_idx')],
            },
        ),
    ]
