# Generated by Django 5.1.15 on 2025-12-16 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_resumeprocessing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, help_text='Type of exception (e.g., ValueError, KeyError)', max_length=255)),
                ('error_message', models.TextField(help_text='Error message from the exception')),
                ('error_traceback', models.TextField(help_text='Full traceback of the error')),
                ('error_hash', models.CharField(db_index=True, help_text='Unique hash for error deduplication (file+function+line+type)', max_length=64)),
                ('file_path', models.CharField(db_index=True, help_text='Relative path to the file where error occurred', max_length=500)),
                ('function_name', models.CharField(db_index=True, help_text='Function/method name where error occurred', max_length=255)),
                ('line_number', models.IntegerField(help_text='Line number where error occurred')),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, db_index=True, help_text='URL path that triggered the error', max_length=2000, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Request GET/POST data (sensitive data filtered)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('status_code', models.IntegerField(default=500, help_text='HTTP status code returned')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Whether this error has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the error was marked as resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the error was resolved', null=True)),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this exact error has occurred')),
                ('first_occurred', models.DateTimeField(auto_now_add=True, help_text='When this error first occurred')),
                ('last_occurred', models.DateTimeField(auto_now=True, db_index=True, help_text='Most recent occurrence of this error')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Error severity level', max_length=20)),
                ('environment', models.CharField(default='development', help_text='Environment where error occurred (development/production)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this error record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this error record was last updated')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who encountered the error (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'db_table': 'error_logs',
                'ordering': ['-last_occurred'],
                'indexes': [models.Index(fields=['error_type', 'is_resolved'], name='error_logs_error_t_d56bac_idx'), models.Index(fields=['file_path', 'function_name'], name='error_logs_file_pa_15a579_idx'), models.Index(fields=['is_resolved', '-last_occurred'], name='error_logs_is_reso_9f7b53_idx'), models.Index(fields=['severity', '-created_at'], name='error_logs_severit_f50532_idx'), models.Index(fields=['error_hash', '-last_occurred'], name='error_logs_error_h_557d9f_idx')],
            },
        ),
    ]
